name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: average
      id: average
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: average
        setup-command: ''
        command: gcc -o hw4-1 hw4-1.c && ./hw4-1
        input: 10 20 40
        expected-output: Average is 23
        comparison-method: contains
        timeout: 10
        max-score: 10
    - name: positive
      id: positive
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: positive
        setup-command: ''
        command: gcc -o hw4-2 hw4-2.c && ./hw4-2
        input: '1'
        expected-output: Positive
        comparison-method: contains
        timeout: 10
        max-score: 5
    - name: negative
      id: negative
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: negative
        setup-command: ''
        command: gcc -o hw4-2 hw4-2.c && ./hw4-2
        input: "-2"
        expected-output: Negative or zero
        comparison-method: contains
        timeout: 10
        max-score: 5
    - name: entropy
      id: entropy
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: entropy
        setup-command: ''
        command: gcc -o hw4-3 hw4-3.c -lm && ./hw4-3
        input: '0.7'
        expected-output: '0.881291'
        comparison-method: contains
        timeout: 10
        max-score: 10
    - name: larger
      id: larger
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: larger
        setup-command: ''
        command: gcc -o hw4-4 hw4-4.c  &&./hw4-4
        input: 10 100
        expected-output: '100'
        comparison-method: contains
        timeout: 10
        max-score: 10
    - name: advpositive
      id: advpositive
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: advpositive
        setup-command: ''
        command: gcc -o ahw4-1 ahw4-1.c  &&./ahw4-1
        input: '10 '
        expected-output: 10 is a positive number
        comparison-method: contains
        timeout: 10
        max-score: 3
    - name: advnegative
      id: advnegative
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: advnegative
        setup-command: ''
        command: gcc -o ahw4-1 ahw4-1.c  &&./ahw4-1
        input: "-1"
        expected-output: "-1 is a negative number"
        comparison-method: contains
        timeout: 10
        max-score: 3
    - name: advnzero
      id: advnzero
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: advnzero
        setup-command: ''
        command: gcc -o ahw4-1 ahw4-1.c  &&./ahw4-1
        input: "0"
        expected-output: "You entered zero"
        comparison-method: contains
        timeout: 10
        max-score: 4
    - name: advmaxval
      id: advmaxval
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: advmaxval
        setup-command: ''
        command: gcc -o ahw4-2 ahw4-2.c  &&./ahw4-2
        input: 10 20 30
        expected-output: Max is 30
        comparison-method: contains
        timeout: 10
        max-score: 10
    - name: advquadratic
      id: advquadratic
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: advquadratic
        setup-command: ''
        command: gcc -o ahw4-3 ahw4-3.c -lm &&./ahw4-3
        input: 1 3 2
        expected-output: "-1 -2"
        comparison-method: contains
        timeout: 10
        max-score: 5
    - name: advquadratic2
      id: advquadratic2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: advquadratic2
        setup-command: ''
        command: gcc -o ahw4-3 ahw4-3.c -lm &&./ahw4-3
        input: 0 3 2
        expected-output: "0.666667"
        comparison-method: contains
        timeout: 10
        max-score: 5
    - name: meal1
      id: meal1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: meal1
        setup-command: ''
        command: gcc -o hw4-5 hw4-5.c  && ./hw4-5
        input: 160 100
        expected-output: Let's reduce sweets
        comparison-method: contains
        timeout: 10
        max-score: 3
    - name: meal2
      id: meal2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: meal2
        setup-command: ''
        command: gcc -o hw4-5 hw4-5.c  && ./hw4-5
        input: 160 51
        expected-output: Eat some more
        comparison-method: contains
        timeout: 10
        max-score: 3
    - name: meal3
      id: meal3
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: meal3
        setup-command: ''
        command: gcc -o hw4-5 hw4-5.c  && ./hw4-5
        input: Height? 160 Weight? 55
        expected-output: Go for it
        comparison-method: contains
        timeout: 10
        max-score: 4
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        AVERAGE_RESULTS: "${{steps.average.outputs.result}}"
        POSITIVE_RESULTS: "${{steps.positive.outputs.result}}"
        NEGATIVE_RESULTS: "${{steps.negative.outputs.result}}"
        ENTROPY_RESULTS: "${{steps.entropy.outputs.result}}"
        LARGER_RESULTS: "${{steps.larger.outputs.result}}"
        ADVPOSITIVE_RESULTS: "${{steps.advpositive.outputs.result}}"
        ADVNEGATIVE_RESULTS: "${{steps.advnegative.outputs.result}}"
        ADVNZERO_RESULTS: "${{steps.advnzero.outputs.result}}"
        ADVMAXVAL_RESULTS: "${{steps.advmaxval.outputs.result}}"
        ADVQUADRATIC_RESULTS: "${{steps.advquadratic.outputs.result}}"
        ADVQUADRATIC2_RESULTS: "${{steps.advquadratic2.outputs.result}}"
        MEAL1_RESULTS: "${{steps.meal1.outputs.result}}"
        MEAL2_RESULTS: "${{steps.meal2.outputs.result}}"
        MEAL3_RESULTS: "${{steps.meal3.outputs.result}}"
      with:
        runners: average,positive,negative,entropy,larger,advpositive,advnegative,advnzero,advmaxval,advquadratic,advquadratic2,meal1,meal2,meal3
